data:
  build: data

master:
  build: master
  volumes:
    - .:/backup
  volumes_from:
    - data
  ports:
    - "50000:50000"

nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - master:jenkins-master

slave:
  build: slave
  ports:
    - "2222:22"

socat:
  build: socat
  command: -d -d TCP-L:2375,fork UNIX:/var/run/docker.sock
  ports:
    - "2375:2375"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always



